# Generated by Django 3.2.5 on 2021-07-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
